name: Update JSON with Markdown Changes

on:
  push:
    paths:
      - "posts/**/*.md"
      - "postdb.json"

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          sudo apt-get install -y nodejs
          sudo apt-get install -y npm
          npm install gray-matter

      - name: Run the update script
        run: |
          node ./scripts/updateJson.js

      - name: Commit changes and push to Github-io-patch branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b Github-io-patch  # Github-io-patch branch'ine geçiş yap
          git add postdb.json
          git commit -m "Update postdb.json"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:Github-io-patch
